### PR TITLE
Add check for email is assigned with other user or not before sending register email link.

### PR DESCRIPTION
**Pull request by itzmanish**
This should be added so that user won't try to add other's email and with this other user can be saved from email verification spam mails.

### CODE REVIEW

**Comment by itzmanish** [comment]
I haven't added test for this. Someone do this please as i am not good at write tests.

**Comment by avyukta** [comment]
Thanks @apragacz  i will keep trying to fix this. You can focus on other issue. This can teach me alot of things and i don't want to miss it by choosing  **Option 0** that you provided. ;-)

**Comment by itzmanish** [comment]
Thanks @apragacz . I am changing according to your suggestion. and yeah your **Option 0** is the best i choose. It will help me to learn new thing.

> I think that current change is definetely an improvement but it poses minor security threat. That is, you can use the endpoint to guess which emails are in the database and which are not (we currently have similar issue with the reset password and registration, but I will deal with that separately). 

Not telling user that email is registered or not, is not a good idea. Running away from problem is not a good idea. However i have a solution to prevent spamming users using our email service.
What we can do is we can set a rate limit to send reset link or changing email link only 3-4 times a day. That will reduce spamming of mail to registered user.

> Another issue what if someone know the email of a user which is registered.

That won't affect the server because if attacker knows the email of registered user in our database they can only spam that email by other email service which user can report spam or it will automatically reported by spam by the user email provider.

One other important feature that should be add . That is if someone changing email address then there should be an otp verification email to old email address to verify the authenticity of the user that it is indeed the authentic user not an attacker who got somehow the login of that victim user.

**Comment by apragacz** [comment]
Hi @itzmanish,
Thanks for the changes! I will merge your changes soon. Below is additional commentary explaining my position: 

> Not telling user that email is registered or not, is not a good idea.

I agree with you, but I think we differ in opinion how to that. Let's explain what I mean by using following usecases. Let's say that the user Alice wants to register (change) her e-mail to another one:

*   usecase A:
    another e-mail is unused by any account (default use case)
*   usecase B:
    another e-mail is used by an account which belongs to Alice
*   usecase C:
    another e-mail is used by an account wihich belongs to Bob (not Alice)

In case B, Alice might be informed that the e-mail is already used (it would be nice from the UX perspective to have it); in case C she shouldn't.
And that's not just my opinion (about case C), OWASP guidelines say exactly the same:

https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#authentication-and-error-messages

Now I think we could easily achieve that by modifying the register e-mail template - instead of returing the verification URL, we could return a information that given address is already in use. This way Alice would receive that information in case B and in case C Bob would receive it, but Alice wouldn't.

So I will merge the changes, but then implement the solution I described above.

> What we can do is we can set a rate limit to send reset link or changing email link only 3-4 times a day. That will reduce spamming of mail to registered user.

I think rate limiting / throttling is something which we could consider to add not only to this view but to other ones (perhaps another issue?) But it definetely should be configurable and disabled by default, as users may have different throttling requirements. Therefore I think that this is not a good solution to this particular problem.

> That won't affect the server because if attacker knows the email of registered user in our database they can only spam that email by other email service which user can report spam or it will automatically reported by spam by the user email provider.

Sorry, but that sounds for me like a poor man's explanation for not abiding to good security practices (like in the OWASP guidelines above).

> One other important feature that should be add . That is if someone changing email address then there should be an otp verification email to old email address to verify the authenticity of the user that it is indeed the authentic user not an attacker who got somehow the login of that victim user.

This is an interesting idea, but I think is impractical, because:

*   The user needs to be authenticated when performing e-mail registration (change). If one hacks into an account, then the damage is already done. In this scenario the attacker couldn't change the e-mail but could do anything else.
*   The verification would be overcomplicated, because the user would need to confirm both from the old and the new e-mail address.
*   There may be cases that the user for some reason loses access to the e-mail, but still can login into his/her account. It would be impossible for him/her to change the e-mail to a new one.

However, I think that sending an extra e-mail to the old e-mail about the e-mail change could be practical solution to at least inform the user that something fishy is going on so he/she could contact the admin (perhaps another issue?).

**Pull request merged**
